### ISSUE TITLE
Create 3 html files

### ISSUE THREAD

**Issue by Andres-CS** [myNJITprojects/WebCommerce_IS_601_103#1]
Create 3 HTML (@ShravyaKudlu  and @suraganigeetha )

- index.html
- shop_page.html
- cart_page.html

Create 1 or 2 CSS files (@ShravyaKudlu  and @suraganigeetha )
- Use the CSS file for the style you want to give to the html pages

Create 1 Javascript file (@Andres-CS )
- This single js file will hold all the functions that will interact with the API DJango

**Comment by ShravyaKudlu** [comment]
I have created 3 HTML page and the stylesheet.css, maybe we can discuss today after class what are the functionalities or maybe schedule a GMeet.
Did you make any changes?
